### ISSUE TITLE
[RFC] License

### ISSUE THREAD

**Issue by ten3roberts** [ten3roberts/ivy#3]
Currently, the license is without a license.

I am debating between using either the MIT-2 or BSD-3 clause.

Are there preference for the current users of this library and the use case for the license of choice?

**Comment by kevinpthorne** [comment]
I am struggling to differentiate the two. Are there any notable differences?

**Comment by ten3roberts** [comment]
They are quite similar, and they are compatible.

BSD is a bit more clear on what "THE SOFTWARE" means and is a bit less vague.

The BSD 3-clause adds a non endorsement clause which states that you cannot use the logo or name for endorsement/marketing reasons. This can protect your product from being associated to a bad name, though it is not as much of a worry for game engines.

Otherwise, they are the same.
